name: Create conda environment with docker badger-env

on:
  push:
    branches:
      - main
      - test_build

jobs:
  build:
    env:
      ENVIRONMENT_NAME: dual-e-pred-beta-env
    runs-on: ubuntu-latest
    name: Build environment
    steps:
      - name: Build environment
        uses: slaclab/lcls-rhel6-conda-pack@v1.1
